### ISSUE TITLE
NoMethodError: undefined method `[]' for Matrix:Module

### ISSUE THREAD

**Issue by michaelachrisco** [jpmckinney/tf-idf-similarity#18]
I ran the example and ran into an error:
```Ruby
NoMethodError: undefined method `[]' for Matrix:Module
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/tf-idf-similarity-0.1.4/lib/tf-idf-similarity/matrix_methods.rb:131:in `initialize_matrix'
```

```
2.2.2 :001 > require 'matrix'
 => false 
2.2.2 :002 > require 'tf-idf-similarity'
 => false 
2.2.2 :003 > document1 = TfIdfSimilarity::Document.new("Lorem ipsum dolor sit amet...")
 => #<TfIdfSimilarity::Document:0x007f8ed3e482e8 @text="Lorem ipsum dolor sit amet...", @id=70125708525940, @tokens=nil, @term_counts={"lorem"=>1, "ipsum"=>1, "dolor"=>1, "sit"=>1, "amet"=>1}, @size=5> 
2.2.2 :004 > document2 = TfIdfSimilarity::Document.new("Pellentesque sed ipsum dui...")
 => #<TfIdfSimilarity::Document:0x007f8ed3e21b98 @text="Pellentesque sed ipsum dui...", @id=70125708447180, @tokens=nil, @term_counts={"pellentesque"=>1, "sed"=>1, "ipsum"=>1, "dui"=>1}, @size=4> 
2.2.2 :005 > document3 = TfIdfSimilarity::Document.new("Nam scelerisque dui sed leo...")
 => #<TfIdfSimilarity::Document:0x007f8ed3e1f8c0 @text="Nam scelerisque dui sed leo...", @id=70125708442720, @tokens=nil, @term_counts={"nam"=>1, "scelerisque"=>1, "dui"=>1, "sed"=>1, "leo"=>1}, @size=5> 
2.2.2 :006 > corpus = [document1, document2, document3]
 => [#<TfIdfSimilarity::Document:0x007f8ed3e482e8 @text="Lorem ipsum dolor sit amet...", @id=70125708525940, @tokens=nil, @term_counts={"lorem"=>1, "ipsum"=>1, "dolor"=>1, "sit"=>1, "amet"=>1}, @size=5>, #<TfIdfSimilarity::Document:0x007f8ed3e21b98 @text="Pellentesque sed ipsum dui...", @id=70125708447180, @tokens=nil, @term_counts={"pellentesque"=>1, "sed"=>1, "ipsum"=>1, "dui"=>1}, @size=4>, #<TfIdfSimilarity::Document:0x007f8ed3e1f8c0 @text="Nam scelerisque dui sed leo...", @id=70125708442720, @tokens=nil, @term_counts={"nam"=>1, "scelerisque"=>1, "dui"=>1, "sed"=>1, "leo"=>1}, @size=5>] 
2.2.2 :007 > model = TfIdfSimilarity::TfIdfModel.new(corpus)
NoMethodError: undefined method `[]' for Matrix:Module
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/tf-idf-similarity-0.1.4/lib/tf-idf-similarity/matrix_methods.rb:131:in `initialize_matrix'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/tf-idf-similarity-0.1.4/lib/tf-idf-similarity/term_count_model.rb:27:in `initialize'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/tf-idf-similarity-0.1.4/lib/tf-idf-similarity/model.rb:12:in `new'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/tf-idf-similarity-0.1.4/lib/tf-idf-similarity/model.rb:12:in `initialize'
	from (irb):7:in `new'
	from (irb):7
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/michaelchrisco/dev/development/subreddit-relations/bin/rails:8:in `<top (required)>'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/commands/rails.rb:6:in `call'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:183:in `block in serve'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:156:in `fork'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:156:in `serve'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/michaelchrisco/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/michaelchrisco/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.2.2 :008 >
```

**Comment by jpmckinney** [comment]
This is very strange. `Matrix[[1,2,3]]` runs just fine in Ruby 2.2.2, which is pretty much all that's happening on the line that errors.

**Comment by michaelachrisco** [comment]
True. The offending line is here:
```ruby
    # @param [Array<Array>] array matrix rows
    # @return [GSL::Matrix,NArray,NMatrix,Matrix] a matrix
    def initialize_matrix(array)
      case @library
      when :gsl
        GSL::Matrix[*array]
      when :narray
        NArray[*array]
      when :nmatrix # @see https://github.com/SciRuby/nmatrix/issues/91#issuecomment-18870619
        NMatrix.new(:dense, [array.size, array.empty? ? 0 : array[0].size], array.flatten, :float64)
      else
        #offender
        Matrix[*array]
      end
    end
```
I'll take a look when I have time to see if it is my local setup or a combo of another gem.

**Comment by jpmckinney** [comment]
Any luck?

**Comment by michaelachrisco** [comment]
I was never able to get it working on 10.10. Ill try and give you an update when I have more time.

**Comment by masterrr** [comment]
Hmm. Facing the same issue on 10.11. Runs just fine in irb, fails when used in rails controller (ruby 2.2.0p0)

```document1 = TfIdfSimilarity::Document.new("keep")
    document2 = TfIdfSimilarity::Document.new("keep")
    corpus = [document1, document2]
    model = TfIdfSimilarity::TfIdfModel.new(corpus)```
![screen shot 2016-01-04 at 8 30 11 pm](https://cloud.githubusercontent.com/assets/720966/12097031/fa29980a-b321-11e5-83e9-85cd38ba7a7d.png)

**Comment by jpmckinney** [comment]
Does putting `::Matrix[]` in a controller raise the same exception?

**Comment by masterrr** [comment]
Yes
```undefined method `[]' for Matrix:Module```

Any ideas I can try or hints which way to go to fix it?

**Comment by jpmckinney** [comment]
Have you done `require 'matrix'` somewhere?

Make sure you (or any other code) aren't defining a `Matrix` module that interferes with Ruby's own Matrix module.

**Comment by masterrr** [comment]
Not defining Matrix modules myself anywhere, done `require 'matrix'` right in the controller

**Comment by jpmckinney** [comment]
It's very unusual for `::Matrix[]` to cause an error in the Rails environment, but not in the Ruby console... Are you using the Spring gem by any chance?

**Comment by masterrr** [comment]
Nope. No spring gem, having this issue on empty Rails setup
`rails -v
Rails 4.2.5
`

**Comment by jpmckinney** [comment]
In a Rails console, can you run:

```
require 'matrix'
::Matrix[]
```

And if that works, open a new Rails console and try:

```
require 'matrix'
require 'tf-idf-similarity'
::Matrix[]
```

**Comment by masterrr** [comment]
```
 DISABLE_SPRING=1 rails c
Loading development environment (Rails 4.2.5)
irb(main):001:0> require 'matrix'
=> false
irb(main):002:0> ::Matrix[]
NoMethodError: undefined method `[]' for Matrix:Module
	from (irb):2
	from /Users/master/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
	from /Users/master/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from /Users/master/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/master/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/master/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
```

**Comment by jillianefoley** [comment]
FWIW, I'm seeing this same issue in my Rails console (v 4.2.5.1) but `::Matrix[]` works just fine in IRB.

**Comment by grych** [comment]
Looks like there is a gem called 'matrix' - https://rubygems.org/gems/matrix
It is literally empty, but when you put it in your `Gemfile` it will override "Matrix" constant. 

So, the solution is to remove this line:

    gem 'matrix'

from the `Gemfile`.

**Comment by michaelachrisco** [comment]
Nice @grych ill have to give this a shot and see if this fixes the issue.

**Comment by jpmckinney** [comment]
I've added a note to the readme: https://github.com/jpmckinney/tf-idf-similarity#troubleshooting
